# Generated by Django 4.0.6 on 2022-07-13 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farminfo',
            fields=[
                ('farmid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('toggle', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='farmdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('barometric', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('farmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapi.farminfo')),
            ],
        ),
    ]
