# Generated by Django 4.0.6 on 2022-07-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='healthdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heartrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
